GET http://localhost:3000/tasks


###
GET http://localhost:3000/tasks/latest

###
GET  http://localhost:3000/tasks/1

###
GET http://localhost:3000/tasks?take=2&skip=2



###
DELETE http://localhost:3000/tasks/3



###
PATCH http://localhost:3000/tasks
Content-Type: application/json

{
    "id" : 2,
    "Date": "2023-08-19T12:00:00Z",
    "dateStart": "2023-08-19T12:00:00Z",
    "dateEnd": "2023-08-20T12:00:00Z",
    "type": "hiuhuhuh",
    "supply": "1",
    "supplyFile": "1",
    "devis": "1",
    "endTask": true,
    "result": "1",
    "followupBool": true,
    "followupAutre": "asdljansdjk"
}

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "clientName": "Client Name",
  "clientNumber": "123456789",
  "distance" : 23,
  "image" : "bruh",
  "taskData": {
    "Date": "2023-08-19T12:00:00Z",
    "dateStart": "2023-08-19T12:00:00Z",
    "dateEnd": "2023-08-20T12:00:00Z",
    "type": "bruh",
    "supply": "1",
    "supplyFile": "1",
    "devis": "1",
    "endTask": true,
    "result": "1",
    "followupBool": true,
    "followupAutre": "asdljansdjk",
    "client": "1"
  }
}

