GET http://localhost:3000/users

###
GET  http://localhost:3000/users/1

###
GET http://localhost:3000/users?take=2&skip=2

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "username5",
    "email":"user5@gmail.com",
    "image":"user5 image",
    "password":"user5",
    "role": "ADMIN"
}

###
DELETE http://localhost:3000/users/4



###
PATCH http://localhost:3000/users
Content-Type: application/json

{
    "id" : 3,
    "name" : "username3",
    "email":"user3333@gmail.com",
    "image":"user3 image",
    "password":"user3",
    "role": "USER"
}

// to test user images
###
GET http://192.168.1.146:3000/uploads/uploads/330806820_6226543644098040_99468803775825536_n.jpg